# This role sets up the property downloads.php.net with Apache together with the php module
# It uses self-signed SSL certs

- name: Enable extra PHP extensions
  shell: "phpenmod {{ item }}"
  args:
    creates: "/etc/php/{{ php_version }}/apache2/conf.d/20-{{ item }}.ini"
  loop:
    - curl
    - zip
  notify: reload apache

- name: Enable 'userdir' Apache module
  command: a2enmod {{ item }}
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  loop:
    - userdir
  notify: reload apache

- name: create local box
  file:
    state: directory
    dest: "{{ downloads_box }}"
    mode: "755"

- name: Add Apache config for downloads.php.net
  template:
    src: templates/downloads.php.net.conf
    dest: "/etc/apache2/sites-available/{{ downloads_config_file }}"
  notify: reload apache

- name: Enable config file
  shell: "a2ensite {{ downloads_config_file }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ downloads_config_file }}"
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

# Create the windows user which is used for storing all windows downloads
- name: Add 'windows' user
  user:
    name: "windows"
    create_home: yes
    state: present
    shell: /usr/sbin/nologin

- include_tasks: deploy.yml

# Backup entire downloads home directory as the disk is full of windows downloads and RC downloads,
# which are stored in people’s home directories
- name: Store pre-backup/post-backup scripts
  template:
    src: "templates/{{ item }}"
    dest: "/local/systems/{{ item }}"
    mode: 0700
  loop:
  - record-users.sh
  - restore-users-and-home-permissions.sh

- name: Run backup tasks
  include_role:
    name: backup_property
  vars:
    property: downloads
    backup_paths: [ "{{ downloads_home_dir }}" ]
    pre_backup_script: "/local/systems/record-users.sh"
    post_restore_script: "/local/systems/restore-users-and-home-permissions.sh"
