#!/bin/sh

echo "Building for " $1
date

echo "Removing old dirs"
rm -rf html php output
date

echo "Running configure"
php{{ php_version }} {{ rsync_repositories_dir }}/phpdoc-git/doc-base/configure.php --with-lang=$1 --disable-libxml-check --disable-segfault-speed || exit 1
date

echo "Running test and build"
php{{ php_version }} {{ rsync_repositories_dir }}/phpdoc/phd/render.php --color false --package PHP --format php --format xhtml --format bigxhtml --format tocfeed -d {{ rsync_repositories_dir }}/phpdoc-git/doc-base/.manual.xml || exit 2
date

cd output

echo "Moving the TOC feed to correct folder"
mv php-tocfeed php-web/feeds

echo "Zipping downloadable manuals"
gzip -9 php-bigxhtml.html -c > php_manual_$1.html.gz
tar -czf php_manual_$1.tar.gz php-chunked-xhtml
date

# Original Production Environment
echo "Create mirrors download directory"
mkdir -p {{ rsync_mirrors_dir }}/phpweb/distributions/manual/

echo "Copying manuals to correct place"
cp -p php_manual_$1.html.gz {{ rsync_mirrors_dir }}/phpweb/distributions/manual/
if [ $? -eq 0 ]; then
	cp -p php_manual_$1.tar.gz {{ rsync_mirrors_dir }}/phpweb/distributions/manual/
else
	echo "FAILED COPYING html.gz INTO DISTRO/MANUAL FOLDER"
fi
date

echo "Copying to rsync space"
cp -rp php-web {{ rsync_mirrors_dir }}/phpweb/manual
if [ $? -eq 0 ]; then
	cd {{ rsync_mirrors_dir }}/phpweb/manual
	rm -rf $1; cp -R php-web $1 # can't move it (yet) as we need it for the preview / php-www-web module too
else
	echo "FAILED COPYING php-web TO THE MANUAL FOLDER"
fi
date

# Preview Environment
# - the manual needs to make it into distributions at some point, but we're ignoring distributions for now
#echo "Create mirrors download directory"
#mkdir -p {{ rsync_mirrors_dir }}/phpweb/distributions/manual/

#echo "Copying manuals to correct place"
#cp -p php_manual_$1.html.gz {{ rsync_mirrors_dir }}/phpweb/distributions/manual/
#if [ $? -eq 0 ]; then
#	cp -p php_manual_$1.tar.gz {{ rsync_mirrors_dir }}/phpweb/distributions/manual/
#else
#	echo "FAILED COPYING html.gz INTO DISTRO/MANUAL FOLDER"
#fi
#date

echo "Copying to rsync space"
cp -rp php-web {{ rsync_mirrors_dir }}/php-www-web/public/manual
if [ $? -eq 0 ]; then
	cd {{ rsync_mirrors_dir }}/php-www-web/public/manual
	rm -rf $1; mv php-web $1
else
	echo "FAILED COPYING php-web TO THE MANUAL FOLDER"
fi
date

echo "Done"
