#!/bin/bash
# Production Site
cd "{{ rsync_repositories_dir }}"
git clone https://github.com/php/web-php.git phpweb
cd "{{ rsync_repositories_dir }}"/phpweb
git clone https://github.com/php/web-php-distributions.git distributions

# Preview Site
cd "{{ rsync_repositories_dir }}"
git clone https://github.com/php/web-php.git php-www-web
cd "{{ rsync_repositories_dir }}"/php-www-web
git checkout preview
cd "{{ rsync_repositories_dir }}"/php-www-web/public
git clone https://github.com/php/web-php-distributions.git distributions

cd "{{ rsync_repositories_dir }}"
git clone https://github.com/php/phd.git phpdoc/phd

cd "{{ rsync_mirrors_dir }}"
git clone https://github.com/php/web-doc.git docweb
git clone https://github.com/php/web-pecl.git peclweb
git clone https://github.com/php/web-analytics.git php-analytics-web
git clone https://github.com/php/web-bugs.git php-bugs-web
git clone https://github.com/php/web-downloads.git php-downloads-web
git clone https://github.com/php/doc-gtk.git php-gtk-doc
git clone https://github.com/php/web-gtk.git php-gtk-web
git clone https://github.com/php/web-master.git php-main-web
git clone https://github.com/php/web-master.git php-master-web
git clone https://github.com/php/web-news.git php-news-web
git clone https://github.com/php/web-people.git php-people-web
git clone https://github.com/php/web-shared.git php-shared
git clone https://github.com/php/web-wiki.git php-wiki
git clone https://github.com/php/web-qa.git qaweb
git clone https://github.com/php/web-pres2.git talks
git clone https://github.com/php/php-sdk-binary-tools php-sdk-binary-tools

for i in talks; do
  cd "{{ rsync_mirrors_dir }}"/$i
  git clone https://github.com/php/presentations.git presentations
done

for i in docweb php-people-web qaweb php-main-web php-master-web php-news-web php-bugs-web php-gtk-web talks; do
  cd "{{ rsync_mirrors_dir }}"/$i
  git clone https://github.com/php/web-shared.git shared
done

cd "{{ rsync_mirrors_dir }}"/php-wiki/dokuwiki
git clone https://github.com/php/web-shared.git shared
