#!/bin/sh

cd {{ backup_dir }}

# Redirect all output to the restore.log
DOW=`date +%w`
exec > "/local/systems/restore-{{ property }}-${DOW}.log" 2>&1

echo "[$(date)] Starting restore process..."

# Environment Variables
export AWS_ACCESS_KEY_ID="{{ DO_access_key }}"
export AWS_SECRET_ACCESS_KEY="{{ DO_secret_key }}"
export RESTIC_PASSWORD="{{ restic_password }}"

# Do restores of databases (assume that root can always read them)
{% if backup_dbs is defined() %}
{% for backup_db in backup_dbs %}

    # restore database {{ backup_db }}
    restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/{{ property }} restore latest -t "{{ restore_dir }}" --path "/local/{{ backup_db }}.sql"
    exit_status=$?
    echo "restic status: " $exit_status

    if [ $exit_status -eq 0 ]; then
      echo "[$(date)] restic download completed."

      mysql -u root "{{ backup_db }}" < "{{ restore_dir }}/local/{{ backup_db }}.sql"

    else
      echo "[$(date)] Could not download data."
    fi

    # Removing temporary data
    rm -rf "{{ restore_dir }}"

{% endfor %}
{% endif %}

# Do restores of directories
{% if backup_paths is defined() %}
{% for backup_path in backup_paths %}

    # restore path {{ backup_path }}
    restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/{{ property }} restore latest -t "{{ restore_dir }}" --path "{{ backup_path }}"
    exit_status=$?
    echo "restic status: " $exit_status

    if [ $exit_status -eq 0 ]; then
      echo "[$(date)] restic download completed."

      cp -a "{{ restore_dir }}{{ backup_path }}/"* "{{ backup_path }}"

    else
      echo "[$(date)] Could not download data."
    fi

{% endfor %}

{% if post_restore_script is defined() %}
    echo "[$(date)] running post-backup-script {{ post_restore_script }}"
    {{ post_restore_script }}
{% endif %}

    # Removing temporary data
    rm -rf "{{ restore_dir }}"

{% endif %}

echo "[$(date)] Restore process finished successfully."
