property: "qa"

qa_domain: "{{ property }}.{{ domain }}"
qa_domain_alias: "{{ property }}.{{ internal_domain }}"

qa_docroot: "{{ common_doc_root }}/{{ qa_domain }}"
qa_config_file: "{{ property }}.{{ domain }}.conf"
