- name: Install Apache with mod-php, php and openssl
  apt:
    name:
      - apache2
      - libapache2-mod-php{{ php_version }}
      - apache2-utils
      - php{{ php_version }}
      - php{{ php_version }}-bz2
      - php{{ php_version }}-cli
      - php{{ php_version }}-curl
      - php{{ php_version }}-gd
      - php{{ php_version }}-intl
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-mysql
      - php{{ php_version }}-sqlite3
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
    state: present
    update_cache: yes

- name: Enable modules in Apache
  command: a2enmod {{ item }}
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  loop:
    - env
    - ssl
    - php{{ php_version }}
    - headers
    - rewrite
    - remoteip
    - status
  notify: reload apache

- name: Add opcache and other local PHP settings
  template:
    src: templates/90-local-settings.ini
    dest: /etc/php/{{ php_version }}/apache2/conf.d/90-local-settings.ini
  notify: reload apache
