- name: Install Apache and PHP on Debian 12
  ansible.builtin.include_tasks: debian-12.yml
  when:
    - ansible_facts['distribution'] == 'Debian'
    - ansible_facts['distribution_major_version'] == '12'

- name: Install Apache and PHP on Debian 13
  ansible.builtin.include_tasks: debian-13.yml
  when:
    - ansible_facts['distribution'] == 'Debian'
    - ansible_facts['distribution_major_version'] == '13'

- name: Create the self-signed SSL Certificate
  include_role:
    name: add_self-signed_certs

- name: Add remoteip logging config
  template:
    src: "templates/{{ mod_remoteip_config_file }}"
    dest: "/etc/apache2/conf-enabled/{{ mod_remoteip_config_file }}"
  notify: reload apache

- name: Create (empty) placeholder file for trusted proxy list
  file:
    path: "{{ remote_ip_trusted_proxy_list }}"
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Create root for all websites
  file:
    state: directory
    dest: "{{ common_doc_root }}"
    mode: "755"
    owner: www-data
    group: www-data
    recurse: true
