# Common Definitions
domain: "php.net"
internal_domain: "internal.php.net"
common_doc_root: "/var/www/sites"
box_dir: "/local/this-box"

# Service Hosts
jumphost: "{{ host | default('jump-ams-1.internal.php.net') }}"

myra_hosts: [ "103.51.164.0/22", "185.85.3.0/24", "213.155.71.142/32", "213.61.215.48/29", "45.112.84.0/22", "45.91.156.0/22", "5.9.89.19/32", "80.90.0.0/20", "82.199.130.0/24", "82.199.157.0/24", "2001:920:198c::fefe/128", "2a01:4a0::/32", "2a01:4f8:162:1346::2/128", "2a02:cb43::/32", "2a02:cb44::/32", "2a02:cb45:101::/48", "2a02:cb46::/32", "2a02:cb47::/32" ]
test_hosts: [ "86.163.232.227" ]

# Used for allowing connections on downloads to come in from in addition to the myra and test hosts
pecl_hosts: [ "104.236.228.160", "157.245.79.146" ]

# Easy DNS hosts to transfer DNS records too
easy_dns_hosts: [ "64.68.200.91" ]

# Private network address that services should rsync from
rsync_address: '{{ hostvars["rsync0"].ansible_eth1.ipv4.address }}'

# These services and servers need (POST) access to main.internal.php.net
access_to_main_hosts:
- 104.236.36.140 # The 'old' lists.php.net server, so that people can subscribe to MLs

systems_email: "systems@{{ domain }}"
master_email: "{{ systems_email }}"

# Non property configuration
bind_php_net_zone_file: "/etc/bind/db.{{ domain }}"
