property: "downloads"

downloads_domain: "downloads.php.net"
downloads_domain_alias: "downloads.internal.php.net"

downloads_docroot: "{{ common_doc_root }}/{{ downloads_domain }}"
downloads_config_file: "{{ property }}.{{ domain }}.conf"

downloads_home_dir: /home
downloads_box: "{{ box_dir }}/{{ property }}"

php_sdk_dir: "{{ downloads_box }}/php-sdk-binary-tools"

windows_public_dir: /home/windows/public_html
windows_builds_tmp_dir: "{{ downloads_box }}/tmp/builds"
windows_builds_options: "--base-directory={{ windows_public_dir }} --builds-directory={{ windows_builds_tmp_dir }}"
