property: "gtk"

gtk_domain: "{{ property }}.{{ domain }}"
gtk_domain_alias: "{{ property }}.{{ internal_domain }}"

gtk_docroot: "{{ common_doc_root }}/{{ gtk_domain }}"
gtk_config_file: "{{ property }}.{{ domain }}.conf"
