#!/bin/sh
#
# build the phd docs using phd itself. inception.

cd "{{ doc_phd_source_dir }}"

php render.php \
    --docbook docs/phd-guide/phd-guide.xml \
    --output '{{ doc_docroot }}/www/phd/docs/' \
    --format 'bigxhtml' \
    --outputfilename 'index.html' \
    --verbose 0
